<?php

namespace AppBundle\Repository;

/**
 * DisplayColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisplayColorRepository extends \Doctrine\ORM\EntityRepository
{
}
