<?php

namespace AppBundle\Repository;

/**
 * LocatedVegetableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocatedVegetableRepository extends \Doctrine\ORM\EntityRepository
{
}
