<?php

namespace AppBundle\Repository;

/**
 * SoilTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoilTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
