<?php

namespace AppBundle\Repository;

/**
 * VegetableCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VegetableCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
