<?php

namespace AppBundle\Repository;

/**
 * VegetableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VegetableRepository extends \Doctrine\ORM\EntityRepository
{
}
