<?php

namespace AppBundle\Repository;

/**
 * VegetableLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VegetableLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
